### Register a user
# @name register
# @description create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "smashraid@gmail.com",
    "name": "Saulo Tsuchida"
}